Algoritmo "resultados"
Var
soma, diferenca, produto, media: real
n1 ,n2: real

Inicio
escreva("escreva um numero:")
leia (n1)
escreva("Escreva outro numero:")
leia (n2)

soma <- n1+n2
diferenca <- n1-n2
produto <- n1*n2
media <- (n1+n2)/2

escreval ("resultado da soma é: ", soma)
escreval ("resultado da diferenca é", diferenca)
escreval ("resultado do prudto é: ", produto)
escreval ("resultado da media é: ", media)


Fimalgoritmo


